[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/api/domains/api.pistatapp.ir/public_html/artisan queue:work redis --queue=default --sleep=3 --tries=3 --timeout=90 --max-time=3600
directory=/home/api/domains/api.pistatapp.ir/public_html
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=api
numprocs=2
redirect_stderr=true
stdout_logfile=/home/api/domains/api.pistatapp.ir/public_html/storage/logs/worker.log
stopwaitsecs=90
