[program:laravel-notifications-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/api/public_html/artisan queue:work redis --queue=notifications,default --sleep=3 --tries=3 --timeout=120 --memory=256 --max-jobs=250 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=api
numprocs=2
redirect_stderr=true
stdout_logfile=/home/api/public_html/storage/logs/notifications-worker.log
stopwaitsecs=3600
